name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Checks out the repository to the runner

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Compile Java
      run: javac -d bin src/App.java  # Compiles Java files to 'bin' directory

    - name: Run Java Program
      run: java -cp bin App  # Runs the compiled program from the 'bin' directory
